### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PoolNet

### ISSUE THREAD

**Issue by ghost** [backseason/PoolNet#12]
I am testing with my own data with the pretrianed model, using ` python main.py --mode='test' --model='results/run-1/models/final.pth' --test_fold='results/run-1-sal-e' --sal_mode='e'  --batch_size=1 --no-cuda`
Here is what i got 
```
Loading pre-trained model from results/run-1/models/final.pth...
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    main(config)
  File "main.py", line 46, in main
    test = Solver(None, test_loader, config)
  File "...\repos\PoolNet\solver.py", line 31, in __init__
    self.net.load_state_dict(torch.load(self.config.model, map_location='cpu'))
  File "...\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PoolNet:
        Unexpected key(s) in state_dict: "block.0.block_in1.0.weight", "block.0.block_in2.0.weight", "block.0.block_mid1.0.0.weight", "block.0.block_mid1.0.1.weight", "block.0.block_mid2.0.0.weight", "block.0.block_mid2.0.1.weight", "block.0.block_out.0.weight", "block.1.block_in1.0.weight", "block.1.block_in2.0.weight", "block.1.block_mid1.0.0.weight", "block.1.block_mid1.0.1.weight", "block.1.block_mid2.0.0.weight", "block.1.block_mid2.0.1.weight", "block.1.block_out.0.weight", "block.2.block_in1.0.weight", "block.2.block_in2.0.weight", "block.2.block_mid1.0.0.weight", "block.2.block_mid1.0.1.weight", "block.2.block_mid2.0.0.weight", "block.2.block_mid2.0.1.weight", "block.2.block_out.0.weight", "block.3.block_in1.0.weight", "block.3.block_in2.0.weight", "block.3.block_mid1.0.0.weight", "block.3.block_mid1.0.1.weight", "block.3.block_mid2.0.0.weight", "block.3.block_mid2.0.1.weight", "block.3.block_out.0.weight", "fuse.trans.0.weight", "fuse.trans.0.bias", "fuse.trans.1.weight", "fuse.trans.1.bias", "fuse.trans.2.weight", "fuse.trans.2.bias", "fuse.trans.3.weight", "fuse.trans.3.bias", "fuse.fuse.weight", "fuse.fuse.bias", "edgeinfo.trans.0.weight", "edgeinfo.trans.2.weight", "edgeinfo.trans.4.weight", "edgeinfo.trans.6.weight".
        size mismatch for score.score.weight: copying a param with shape torch.Size([1, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
```
Do you know what could be the problem?

**Comment by backseason** [comment]
The model in `run-1` is for salient object detection joint training with edge detection.
Use `python joint_main.py ...` instead.

**Comment by ghost** [comment]
It works. Thanks!
