### ISSUE TITLE
backbone 更改

### ISSUE THREAD

**Issue by tuqiangwang** [backseason/PoolNet#25]
你好，我看你们的代码有resent 和vgg做backbone 的，我可以改用其他，例如googlenet，这样代码会是否可以跑通？
如果可以跑通，那backbone 更换过程，需要更改和注意哪些地方

**Comment by backseason** [comment]
可以，你需要修改：
1. `networks/deeplab_resnet.py` 中的backbone部分为你需要的基础网络结构；
2. `networks/deeplab_resnet.py` 中PPM部分对应的channel数；
3. `networks/poolnet.py` 中的`config_*`参数与新的基础网络对齐；
4. 传入新的基础网络的预训练参数（注意输入图像是[0, 255] BGR格式）

对于joint training，修改方式类似。

**Comment by tuqiangwang** [comment]
那您除了resnet和vgg，有其他版本的代码吗？如果有，可以共享一下吗

**Comment by backseason** [comment]
不好意思，现阶段没有。

**Comment by tuqiangwang** [comment]
嗯，谢谢！
那请问，PPM的channel和config_*具体对齐是怎么修改的，我改了很多次，都不成功

**Comment by backseason** [comment]
你可以参考输出的Error信息进行修改，应该不难。

**Comment by tuqiangwang** [comment]
你好，我更改了相关参数，能够开始训练，可是
`The number of parameters: 89934002
epoch: [ 0/15], iter: [    0/30000]  ||  Edge :  3467.4568  ||  Sal :     0.0000  ||  Sum :  3467.4568
Learning rate: 5e-05
Traceback (most recent call last):
  File "joint_main.py", line 108, in <module>
    main(config)
  File "joint_main.py", line 46, in main
    train.train()
  File "/home/tutu/net/other_net/PoolNet/joint_solver.py", line 126, in train
    edge_pred = self.net(edge_image, mode=0)
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tutu/net/other_net/PoolNet/networks/joint_poolnet.py", line 183, in forward
    merge = self.deep_pool[0](conv2merge[0], conv2merge[1], infos[0])
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tutu/net/other_net/PoolNet/networks/joint_poolnet.py", line 55, in forward
    y = self.convs[i](self.pools[i](x))
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 547, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (512x6x12). Calculated output size: (512x0x1). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63
`

**Comment by tuqiangwang** [comment]
你好，我更改了参数，能够开始训练，可是报错了：
The number of parameters: 89934002
epoch: [ 0/15], iter: [    0/30000]  ||  Edge :  3467.4568  ||  Sal :     0.0000  ||  Sum :  3467.4568
Learning rate: 5e-05
Traceback (most recent call last):
  File "joint_main.py", line 108, in <module>
    main(config)
  File "joint_main.py", line 46, in main
    train.train()
  File "/home/tutu/net/other_net/PoolNet/joint_solver.py", line 126, in train
    edge_pred = self.net(edge_image, mode=0)
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tutu/net/other_net/PoolNet/networks/joint_poolnet.py", line 183, in forward
    merge = self.deep_pool[0](conv2merge[0], conv2merge[1], infos[0])
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tutu/net/other_net/PoolNet/networks/joint_poolnet.py", line 55, in forward
    y = self.convs[i](self.pools[i](x))
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tutu/.virtualenvs/env1/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 547, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (512x6x12). Calculated output size: (512x0x1). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63

**Comment by backseason** [comment]
PPM中有一个x8的下采样，所以你应该保证你输入至PPM的feature map的大小在8x8之上。

**Comment by tuqiangwang** [comment]
嗯嗯 已解决

**Comment by tuqiangwang** [comment]
出现了一个新错误，显存是够的啊，不清楚为什么
The number of parameters: 40173858
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
torch.Size([1, 480, 375, 500])
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f6d1020fdd8>>
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/env1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/ubuntu/.virtualenvs/env1/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/home/ubuntu/.virtualenvs/env1/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 494, in Client
    deliver_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 722, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "joint_main.py", line 107, in <module>
    main(config)
  File "joint_main.py", line 46, in main
    train.train()
  File "/home/ubuntu/tq/PoolNet_18/PoolNet/joint_solver.py", line 126, in train
    edge_pred = self.net(edge_image, mode=0)
  File "/home/ubuntu/.virtualenvs/env1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/tq/PoolNet_18/PoolNet/networks/joint_poolnet.py", line 183, in forward
    merge = self.deep_pool[0](conv2merge[0], conv2merge[1], infos[0])
  File "/home/ubuntu/.virtualenvs/env1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/tq/PoolNet_18/PoolNet/networks/joint_poolnet.py", line 56, in forward
    resl = torch.add(resl, F.interpolate(y, x_size[2:], mode='bilinear', align_corners=True))
RuntimeError: CUDA error: out of memory
