### ISSUE TITLE
What's wrong with my usage? Out of memory happened when test model with my own data

### ISSUE THREAD

**Issue by WepLeo** [backseason/PoolNet#3]
## cmd:   
```
python  main.py --mode='test'  --model='run_data/run-0/models/final.pth'  --test_fold='./ret/' --sal_mode='test_data'
```
'run_data/run-0/models/final.pth' is downloaded from the url in README.md  
'test_data' is my own test images with shape (300, 400, 3)  
The pretrained `/dataset/pretrained/resnet50_caffe.pth` and `run-0/models/final.pth` is loaded ok, but error happened when start to test first img.  

## error:
```
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    main(config)
  File "main.py", line 49, in main
    test.test()
  File "/home/wepleo/dplearning/commodity_classification/pytorch/PoolNet-master/solver.py", line 70, in test
    preds = self.net(images)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wepleo/dplearning/commodity_classification/pytorch/PoolNet-master/networks/poolnet_1task.py", line 101, in forward
    conv2merge, infos = self.base(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wepleo/dplearning/commodity_classification/pytorch/PoolNet-master/networks/deeplab_resnet.py", line 197, in forward
    infos.append(self.infos[k](F.interpolate(xls, xs[len(self.infos) - 1 - k].size()[2:], mode='bilinear', align_corners=True)))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
```

**Comment by backseason** [comment]
I have tried PyTorch==0.4.1 with Python 2.7, and it takes about 2GB gpu memory when testing.

**Comment by WepLeo** [comment]
I'm so SORRY!! My fault!! The test  image size is (3000, 4000, 3)
