### ISSUE TITLE
Problems running training

### ISSUE THREAD

**Issue by Goru1890** [backseason/PoolNet#61]
I'm really new in this,

I followed all the steps, but I'm getting this error:

The number of parameters: 68261057
File ./data/DUTS/DUTS-TR/DUTS-TR-Image/DUTS-TR-Image/ILSVRC2014_train_00043234.jpg not exists
File ./data/DUTS/DUTS-TR/DUTS-TR-Image/DUTS-TR-Image/n02108915_1958.jpg not exists
File ./data/DUTS/DUTS-TR/DUTS-TR-Image/DUTS-TR-Image/n03673027_8108.jpg not exists
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    main(config)
  File "main.py", line 41, in main
    train.train()
  File "/home/ups/Documents/Proyectos/vigia/background/PoolNet/solver.py", line 87, in train
    for i, data_batch in enumerate(self.train_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ups/Documents/Proyectos/vigia/background/PoolNet/dataset/dataset.py", line 27, in __getitem__
    sal_image = load_image(os.path.join(self.sal_root, im_name))
  File "/home/ups/Documents/Proyectos/vigia/background/PoolNet/dataset/dataset.py", line 74, in load_image
    in_ -= np.array((104.00699, 116.66877, 122.67892))
ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (3,)

How can I solve it?

**Comment by luoshuifeiyang** [comment]
I meet the same problem , what did you do to solve this problem? Thanks a lot.

**Comment by Goru1890** [comment]
Are running it with python 3?
Be sure that you are using the right image path in the scripts, you can find the images for testing here https://drive.google.com/file/d/1eB-59cMrYnhmMrz7hLWQ7mIssRaD-f4o/view.
